export enum ACTION_TYPES {
  EXPLORE_DATA_REQUESTING = "EXPLORE_DATA_REQUESTING",
  EXPLORE_DATA_SUCCESS = "EXPLORE_DATA_SUCCESS",
  EXPLORE_DATA_ERROR = "EXPLORE_DATA_ERROR",
  LIVE_ANYWHERE_REQUESTING = "LIVE_ANYWHERE_REQUESTING",
  LIVE_ANYWHERE_SUCCESS = "LIVE_ANYWHERE_SUCCESS",
  LIVE_ANYWHERE_ERROR = "LIVE_ANYWHERE_ERROR",
  HYDRATE = "__NEXT_REDUX_WRAPPER_HYDRATE__",
}
